apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r6y748r1o-nodejs
  janus-idp.io/tekton: r6y748r1o-nodejs
  backstage.io/kubernetes-id: r6y748r1o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r6y748r1o-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
